### ISSUE TITLE
Consider StableLib/x25519 implementation instead of tweetnacl

### ISSUE THREAD

**Issue by dlongley** [digitalbazaar/minimal-cipher#2]
See: https://github.com/StableLib/stablelib/tree/master/packages/x25519

We don't need all of tweetnacl -- so we could potentially cut back on size by using the above implementation from the same main contributor of tweetnacl.

**Comment by dmitrizagidulin** [comment]
See also the discussion at https://github.com/digitalbazaar/crypto-ld/issues/48#issuecomment-671466177

**Comment by dlongley** [comment]
These also exist: https://github.com/paulmillr/noble-ed25519 (has x25519 implementation) and  https://www.npmjs.com/package/ed25519-to-x25519.wasm

**Comment by dlongley** [comment]
Addressed by #44.
