### ISSUE TITLE
Optimize decrypt API

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/minimal-cipher#27]
I observed that every `chunk` in a stream decryption involves computing a key agreement key and many other operations.  We are optimizing the computation of KeKs, but it would be much better to no perform the same operation repeatedly.

There's a fixme in the code for implementing a cache: https://github.com/digitalbazaar/minimal-cipher/blob/master/DecryptTransformer.js#L108-L109

**Comment by dlongley** [comment]
Duplicate of #30.
