### ISSUE TITLE
TODO: consider a cache of encrypted_key => CEKs to reduce unwrapping

### ISSUE THREAD

**Issue by JSAssassin** [digitalbazaar/minimal-cipher#37]
- [ ] TODO: consider a cache of encrypted_key => CEKs to reduce unwrapping
      Commit: (4efdf85) Add TODO.
      Fi[DecryptTransformer.js:106](https://github.com/digitalbazaar/minimal-cipher/blob/master/DecryptTransformer.js#L106)
      Dave Longley commented 2 years ago

**Comment by dlongley** [comment]
Duplicate of #30.
