### ISSUE TITLE
TODO: ensure this polyfill is necessary

### ISSUE THREAD

**Issue by JSAssassin** [digitalbazaar/minimal-cipher#38]
- [ ] TODO: ensure this polyfill is necessary
       Commit: (937b290) Use web streams ponyfill if necessary.
       Fi[util-browser.js:9](https://github.com/digitalbazaar/minimal-cipher/blob/master/util-browser.js#L9)
       Dave Longley commented 2 years ago

**Comment by dlongley** [comment]
Web steams ponyfill has been removed -- it must be specified by the app developer as needed.
