### ISSUE TITLE
Consider phasing out web-streams-polyfill after Node 18

### ISSUE THREAD

**Issue by aljones15** [digitalbazaar/minimal-cipher#40]
Node 18 implements [`web-streams`](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V18.md#web-streams-api-experimental) as a global. This means that we can consider dropping the `web-streams-polyfill` in the future once `node >= 18` is more widespread and [browser support for `web-streams` is also widespread](https://caniuse.com/?search=ReadableStream)

**Comment by dlongley** [comment]
The polyfill has been removed as a core dependency. It must be added only by applications that need it.
