### ISSUE TITLE
Chacha20 vs XChacha20 encryption selection

### ISSUE THREAD

**Issue by kdenhartog** [digitalbazaar/minimal-cipher#8]
I noticed that support for `chacha20` has been opted for over `XChacha20` (at least for now is how I read it). Would this implementation be willing to help push for a `XChacha20`/`AES-GCM` only implementation once it's made possible in browsers and deprecate the `chacha20` cipher?

The main concern I have with `chacha20` is that it requires state management of the nonce when 96 bit nonce is used. It feels unnecessary given we can randomly generate the nonce and make them stateless once we support 192 bit nonce. Is this similar to the direction you'd like to go once browser support is added?

**Comment by dlongley** [comment]
@kdenhartog,

> I noticed that support for chacha20 has been opted for over XChacha20 (at least for now is how I read it). Would this implementation be willing to help push for a XChacha20/AES-GCM only implementation once it's made possible in browsers and deprecate the chacha20 cipher?

Most definitely.

> The main concern I have with chacha20 is that it requires state management of the nonce when 96 bit nonce is used. It feels unnecessary given we can randomly generate the nonce and make them stateless once we support 192 bit nonce. Is this similar to the direction you'd like to go once browser support is added?

Absolutely. The *only* reason chacha20 is currently favored over XChaCha20 right now is that implementation support is lacking. We'd be very happy to switch to XChaCha20 and drop support for chacha20.

**Comment by kdenhartog** [comment]
I've just sent off an email to the CFRG at IETF where the RFC is being worked on. Also, I've written an implementation of XChacha20poly1305 in [stablelib](https://github.com/StableLib/stablelib/tree/master/packages/xchacha20poly1305) based on the RFC using the test vectors provided. It might be worth looking into as an interim solution.

**Comment by dlongley** [comment]
Awesome, @kdenhartog, thank you! We will take a look at your implementation and see if we can get it integrated into minimal-cipher here -- and push out a new major release that only uses XChaCha20Poly1305 for the `recommended` mode (removing ChaChaPoly1305).

**Comment by dlongley** [comment]
XChaCha20Poly1305 is now the recommended encryption algorithm for minimal-cipher v1.1. Thanks @kdenhartog for providing the implementation!
