### ISSUE TITLE
node 10.17+ now supports ChaCha20-Poly1305

### ISSUE THREAD

**Issue by dlongley** [digitalbazaar/minimal-cipher#9]
We should use the node version where available. Note: This is still not ideal as we would prefer XChaCha20-Poly1305 for the larger IV, but using native code where available is an improvement.

**Comment by aljones15** [comment]
Not sure if relevant, but can I use it for this: https://caniuse.com/#feat=chacha20-poly1305

**Comment by dlongley** [comment]
@aljones15 -- that caniuse entry is for TLS support in browsers, which isn't relevant here, I don't think.

**Comment by aljones15** [comment]
> @aljones15 -- that caniuse entry is for TLS support in browsers, which isn't relevant here, I don't think.

I did see it was for the node side of this, but it might be useful as this library is run in browsers.

**Comment by dlongley** [comment]
In order to use node's native ChaCha20Poly1305 in XChaCha20Poly1305, we would need to pull out the HChaCHa20 key derivation from `@stablelib` to derive the key and then pass it to node's native API.

**Comment by dlongley** [comment]
https://www.derpturkey.com/chacha20poly1305-aead-with-node-js/

**Comment by dlongley** [comment]
Note: Since chacha20 is available via node, it could be used to build hchacha20 and, in turn, xchacha20.

**Comment by dlongley** [comment]
Addressed by #43.
